spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-flex:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.duegin.notification.entity
  global-config:
    logic-delete-column: deleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  excludes:
    - /api/user/login
    - /api/user/register