#server:
#  servlet:
#    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-flex:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.duegin.notification.entity
  global-config:
    logic-delete-column: deleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  excludes:
    - /api/user/login
    - /api/user/register
    - /doc.html
    - /webjars/**
    - /swagger-resources
    - /v2/api-docs
    - /v3/api-docs
    - /favicon.ico
    - /swagger-ui/**
    - /swagger-ui.html
    - /v3/api-docs/**

#knife4j:
#  enable: true
#  openapi:
#    title: 通知系统
#    description: "旨在**通知**消息"
#    email: 1917764907@qq.com
#    concat: DueGin
#    version: v1.0

# springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
##  group-configs:
##    - group: 'default'
##      paths-to-match: '/**'
##      packages-to-scan: com.duegin.notification.controller
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn