#\u6307\u5B9AMybatis\u7684Mapper\u6587\u4EF6
mybatis-flex:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.duegin.notification.mybatis.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: 1234

